const BASE_URL = process.env.NEXT_PUBLIC_LANDING_URL
const LANDING_BASE_URL = process.env.NEXT_PUBLIC_LANDING_SERVICE_BASE_URL
const PRODUCT_BASE_URL = process.env.NEXT_PUBLIC_PRODUCT_SERVICE_BASE_URL
const REDIRECT_URI = process.env.NEXT_PUBLIC_PLATFORM_URL

export { BASE_URL, LANDING_BASE_URL, PRODUCT_BASE_URL, REDIRECT_URI }
